### ISSUE TITLE
Installation of Atom snap for Linux

### ISSUE THREAD

**Issue by aminya** [UziTech/action-setup-atom#142]
Can you provide an option to setup Atom using snapcraft? 

https://snapcraft.io/atom

**Comment by UziTech** [comment]
I'm not sure how to do that but would be open to PRs.

**Comment by DeeDeeG** [comment]
Snap (the command-line tool) is just another package manager. It's included in the GitHub Actions runners.

You can simply do this on the command-line...

Stable channel:

`sudo snap install atom --classic`

Edge channel:

`sudo snap install atom --edge --classic`

---

After that, you have Atom installed. I haven't tried to do much with it beyond installing it... I know `apm --version` works, but `atom --version` does not work, and both of those commands print an error message before running:

```
mkdir: missing operand
Try 'mkdir --help' for more information.
```

**Comment by UziTech** [comment]
@DeeDeeG If you create a PR I would be happy to review it. 😁👍

**Comment by UziTech** [comment]
I'm going to close this because of the discussion in #153. It doesn't seem like this action should be concerned with where Atom is installed from.
