### ISSUE TITLE
Run apm --version after the installation

### ISSUE THREAD

**Issue by aminya** [UziTech/action-setup-atom#149]
Currently, there is no log or record of the installed Atom. I think the action should run `apm --version` to show the version of the Atom that is installed. This is important for future references to that job.

**Comment by UziTech** [comment]
I thought about that at first, but decided it was just easier for the user to run that command in the next step. That way we don't need to add a setting for people who don't want that for some reason.

**Comment by aminya** [comment]
All the other setting up actions (such as setup-node, setup-python, setup-go, etc) print the version they are installing. If you don't run apm --version, then you should extract the version from the file name.

This is a basic printing that does not require an option. Similar to how none of the other setup-actions do.

Setup-node
https://github.com/actions/setup-node/blob/c46424eee26de4078d34105d3de3cc4992202b1e/src/installer.ts#L108

Setup-python
https://github.com/actions/setup-python/blob/8c5ea631b2b2d5d8840cf4a2b183a8a0edc1e40d/src/setup-python.ts#L24

Setup-go
https://github.com/actions/setup-go/blob/3b4dc6cbed1779f759b9c638cb83696acea809d1/src/installer.ts#L47

**Comment by UziTech** [comment]
I think keeping this action as simple as possible would be better. running `apm --version` isn't hard to do in the configuration.

**Comment by UziTech** [comment]
I suppose if you want to create a PR I could review it.
