### ISSUE TITLE
Select exact Atom version

### ISSUE THREAD

**Issue by davidstraka2** [UziTech/action-setup-atom#171]
Would it be possible to add support for selecting an exact Atom version to use, in addition to the release channels?

This way, if one wants to support e.g. Atom versions from 1.x.y onwards, they could test on the current stable and perhaps beta channels to assert latest versions support, and additionally on the minimum supported 1.x.y version to check that it's backwards compatible (all the API used is present in that older version, etc.).

At least given the same major version, this should give solid reassurance that things will work. If the stable/beta channels get hit with a new major version, that could cause problems, but I don't think there is a way to get around that currently (a way of using the latest minor version of a target major version).

**Comment by UziTech** [comment]
It would be possible if there is a url for the builds for each version.

Currently we are using `https://atom.io/download/windows_zip?channel=${channel}` and specific urls for other platforms. I don't know if there are urls for each version.

**Comment by davidstraka2** [comment]
I'm not so sure about the atom.io website (I quick Google search hasn't led me anywhere), but perhaps the GitHub releases could be used? So e.g. for Windows `https://github.com/atom/atom/releases/download/v${version}/atom-windows.zip` or `https://github.com/atom/atom/releases/download/v${version}/atom-x64-windows.zip`, `${version}` being e.g. `1.54.0`, `1.55.0-beta0`, etc.

**Comment by UziTech** [comment]
That could work. We would have to make sure there is some stability with the names of the files and write some tests. If you would like to create a PR that lets the `channel` be a specific version I would be happy to review it. 😁👍

**Comment by davidstraka2** [comment]
Yeah I took a look and at least the first releases seem available seem to have different set of assets. With over 500 published releases, going though it to find just how often it changed would be quite tedious. There is [this GitHub API](https://docs.github.com/en/rest/reference/repos#list-releases), so it might be faster to do it programmatically. Maybe limiting support for only versions >=1.0.0 could things easier without impacting many people (1.0.0 came out like 6 years ago).

I probably don't have the time to do it properly (including the before mentioned analysis, testing, and so on) for the next couple of months, but if the issue remains open by then, I would love to help and contribute once I'm more available.

**Comment by UziTech** [comment]
I think limiting it to >v1.0.0 should be fine.

After some scripting it looks like the files `atom-windows.zip` `atom-mac.zip` `atom-amd64.deb` are consistent after v1.0.0 and `atom-x64-windows.zip` was added in v1.14.0.

I'm thinking that is all we need to make it work. I will take a look at this more in the next few days.

**Comment by davidstraka2** [comment]
Just noticed that this has been resolved. Thanks @UziTech for taking the time to implement it! I probably wouldn't have found the time to do it myself for like 2 more months. I'll update to v2 in the next few days and make use of this new feature (I'm currently working on an Atom package for my thesis, so this CI action as well as your Jasmine 3 test runner are both of great help to me).
