### ISSUE TITLE
Publish doesn't work due to lack of authentication

### ISSUE THREAD

**Issue by morphy2k** [UziTech/action-setup-atom#214]
Hey, I tried to publish a package using this action. Unfortunately, the operation fails because it does not recognize the previous (successful) login.
https://github.com/morphy2k/linter-revive/runs/2749098886?check_suite_focus=true#step:9:9

Any idea what could be the reason for this?

**Comment by UziTech** [comment]
That seems like a good question for atom or GitHub actions. I have only published with semantic release and [apm config](https://github.com/semantic-release/apm-config)

**Comment by UziTech** [comment]
You can see my usual workflow at https://github.com/UziTech/git-menu/blob/master/.github/workflows/main.yml
