### ISSUE TITLE
Deb download link 404ing

### ISSUE THREAD

**Issue by richrace** [UziTech/action-setup-atom#222]
Not necessarily an issue with this Action template, but the URL here:

https://github.com/UziTech/action-setup-atom/blob/v2/src/setup-atom.js#L60

Returns 404s for Stable and Beta.

This is causing builds to fail: https://github.com/richrace/highlight-selected/pull/240/checks?check_run_id=2912963614

`https://atom.io/download/deb?channel=stable` => `https://atom-installer.github.com/v1.57.0/atom-amd64.deb?s=1620674304&ext=.deb` => `404 Blob Not Found`

**Comment by UziTech** [comment]
I submitted an issue https://github.com/atom/atom/issues/22650

**Comment by UziTech** [comment]
This should be fixed now. Thanks for reporting it. :100:

**Comment by richrace** [comment]
🎉  Awesome thanks for bubbling it up to Atom 👍
