### ISSUE TITLE
Error "is not a Debian format archive" suddenly appeared

### ISSUE THREAD

**Issue by jstritch** [UziTech/action-setup-atom#301]
The action-setup-atom has been working fine for months. Last night it failed twice with the following message:

Run UziTech/action-setup-atom@v[2](https://github.com/jstritch/git-tabular-diff/runs/6078581892?check_suite_focus=true#step:3:2)
  with:
    version: stable
version: stable
folder: /home/runner/work/_temp/atom
/usr/bin/dpkg-deb -x /home/runner/work/_temp/59c71ac2-00f1-4b17-89[3](https://github.com/jstritch/git-tabular-diff/runs/6078581892?check_suite_focus=true#step:3:3)1-eb1a[4](https://github.com/jstritch/git-tabular-diff/runs/6078581892?check_suite_focus=true#step:3:4)83b2[5](https://github.com/jstritch/git-tabular-diff/runs/6078581892?check_suite_focus=true#step:3:5)94 /home/runner/work/_temp/atom
dpkg-deb: error: '/home/runner/work/_temp/59c[7](https://github.com/jstritch/git-tabular-diff/runs/6078581892?check_suite_focus=true#step:3:7)1ac2-00f1-4b17-[8](https://github.com/jstritch/git-tabular-diff/runs/6078581892?check_suite_focus=true#step:3:8)931-eb1a483b2594' is not a Debian format archive
Error: The process '/usr/bin/dpkg-deb' failed with exit code 2

You can check the actions at https://github.com/jstritch/git-tabular-diff

As an aside, the branch protection rules I have setup did not prevent Renovate from auto-merging to master when this occurred.

How do I resolve the problem(s)?

**Comment by UziTech** [comment]
Looks like this is something that Atom broke. We download Atom from `https://atom.io/download/deb?channel=stable` which seems to now just redirect to  `https://github.com/atom/atom/releases/latest` instead of downloading the stable version

**Comment by jstritch** [comment]
It's working now.  Thanks for the speedy response!
