### ISSUE TITLE
Failures during package install and version checking

### ISSUE THREAD

**Issue by thumperward** [UziTech/action-setup-atom#4]
https://github.com/thumperward/auto-create-files/runs/305993144

The specified workflow isn't doing anything clever, yet all of the configured jobs are failing, either when showing versions or when installing dependencies (of which there is only one for this package).

**Comment by UziTech** [comment]
looks like the error is from running `atom ci` when you don't have a `package-lock.json` file.

If you change it to `apm i` it should work.

```
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
```

**Comment by UziTech** [comment]
I created a PR for your PR that should work https://github.com/thumperward/auto-create-files/pull/3
